#######################
# months of year

january:   janvier
february:  février
march:     mars
april:     avril
may:       mai
june:      juin
july:      juillet
august:    août
september: septembre
october:   octobre
november:  novembre
december:  décembre
