#######################
# months of year

january:   gennaio
february:  febbraio
march:     marzo
april:     aprile
may:       maggio
june:      giugno
july:      luglio
august:    agosto
september: settembre
october:   ottobre
november:  novembre
december:  dicembre
