###########################
# known keywords for fixtures


group:      Gruppe

round:   Spieltag|Runde


stage:      Gruppenphase|Qualifikation|Play-off|Finalrunde|K.-o.-Phase


### Knock out rounds

## fix: add playoffs:
round32:        Sechzehntelfinale|1/16 Finale
round16:        Achtelfinale|1/8 Finale
quarterfinals:  Viertelfinale|1/4 Finale
semifinals:     Halbfinale|Semifinale|1/2 Finale
fifthplace:     Spiel um Platz 5
thirdplace:     Spiel um Platz 3
final:          Finale|Endspiel

### Pair matches/games if marked with leg1 n leg2

leg1:  Hin|Hinspiel|Hinspiele
leg2:  Rück|Rückspiel|Rückspiele
