###########################
# known keywords for fixtures


group:     Gruppo


round:      Giornata

stage:    Fase a gironi|Fase a eliminazione diretta
# e.g.
#  Group stage
#  Play off stage|Play-off stage
#  Knockout stage|Knockout stages
#  First stage
#  Second stage
#  Qualifying rounds




### Knockout rounds

## fix: add playoffs + fifthplace


round32:        Sedicesimi di finale
round16:        Ottavi di finale
quarterfinals:  Quarti di finale
semifinals:     Semifinali
thirdplace:     Finale 3ยบ posto
final:          Finale

### Pair matches/games if marked with leg1 n leg2

leg1:  Andata
leg2:  Ritorno
